package com.shinowit.model;

import java.io.Serializable;

public class TauOperinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.OperName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.Pwd
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String linktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.Mobile
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Short sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_OperInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.OperID
     *
     * @return the value of TAu_OperInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.OperID
     *
     * @param operid the value for TAu_OperInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.ID
     *
     * @return the value of TAu_OperInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.ID
     *
     * @param id the value for TAu_OperInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.RoleID
     *
     * @return the value of TAu_OperInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.RoleID
     *
     * @param roleid the value for TAu_OperInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.OperName
     *
     * @return the value of TAu_OperInfo.OperName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.OperName
     *
     * @param opername the value for TAu_OperInfo.OperName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.Pwd
     *
     * @return the value of TAu_OperInfo.Pwd
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.Pwd
     *
     * @param pwd the value for TAu_OperInfo.Pwd
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.Address
     *
     * @return the value of TAu_OperInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.Address
     *
     * @param address the value for TAu_OperInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.LinkTel
     *
     * @return the value of TAu_OperInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.LinkTel
     *
     * @param linktel the value for TAu_OperInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel == null ? null : linktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.QQ
     *
     * @return the value of TAu_OperInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.QQ
     *
     * @param qq the value for TAu_OperInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.Email
     *
     * @return the value of TAu_OperInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.Email
     *
     * @param email the value for TAu_OperInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.Mobile
     *
     * @return the value of TAu_OperInfo.Mobile
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.Mobile
     *
     * @param mobile the value for TAu_OperInfo.Mobile
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.SortID
     *
     * @return the value of TAu_OperInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Short getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.SortID
     *
     * @param sortid the value for TAu_OperInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSortid(Short sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_OperInfo.State
     *
     * @return the value of TAu_OperInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_OperInfo.State
     *
     * @param state the value for TAu_OperInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TauOperinfo other = (TauOperinfo) that;
        return (this.getOperid() == null ? other.getOperid() == null : this.getOperid().equals(other.getOperid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getOpername() == null ? other.getOpername() == null : this.getOpername().equals(other.getOpername()))
            && (this.getPwd() == null ? other.getPwd() == null : this.getPwd().equals(other.getPwd()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLinktel() == null ? other.getLinktel() == null : this.getLinktel().equals(other.getLinktel()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOperid() == null) ? 0 : getOperid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getOpername() == null) ? 0 : getOpername().hashCode());
        result = prime * result + ((getPwd() == null) ? 0 : getPwd().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLinktel() == null) ? 0 : getLinktel().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }
}