package com.shinowit.model;

import java.io.Serializable;

public class TauPower implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.MenuName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.URL
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_Power.url_id
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String urlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAu_Power
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.MenuID
     *
     * @return the value of TAu_Power.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.MenuID
     *
     * @param menuid the value for TAu_Power.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.ID
     *
     * @return the value of TAu_Power.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.ID
     *
     * @param id the value for TAu_Power.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.MenuName
     *
     * @return the value of TAu_Power.MenuName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.MenuName
     *
     * @param menuname the value for TAu_Power.MenuName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.URL
     *
     * @return the value of TAu_Power.URL
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.URL
     *
     * @param url the value for TAu_Power.URL
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.SortID
     *
     * @return the value of TAu_Power.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.SortID
     *
     * @param sortid the value for TAu_Power.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSortid(String sortid) {
        this.sortid = sortid == null ? null : sortid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.State
     *
     * @return the value of TAu_Power.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.State
     *
     * @param state the value for TAu_Power.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_Power.url_id
     *
     * @return the value of TAu_Power.url_id
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_Power.url_id
     *
     * @param urlId the value for TAu_Power.url_id
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setUrlId(String urlId) {
        this.urlId = urlId == null ? null : urlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Power
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TauPower other = (TauPower) that;
        return (this.getMenuid() == null ? other.getMenuid() == null : this.getMenuid().equals(other.getMenuid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMenuname() == null ? other.getMenuname() == null : this.getMenuname().equals(other.getMenuname()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getUrlId() == null ? other.getUrlId() == null : this.getUrlId().equals(other.getUrlId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Power
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuid() == null) ? 0 : getMenuid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMenuname() == null) ? 0 : getMenuname().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getUrlId() == null) ? 0 : getUrlId().hashCode());
        return result;
    }
}