package com.shinowit.model;

import java.io.Serializable;

public class TauRoleinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_RoleInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_RoleInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_RoleInfo.RoleName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_RoleInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Short sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAu_RoleInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_RoleInfo.RoleID
     *
     * @return the value of TAu_RoleInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_RoleInfo.RoleID
     *
     * @param roleid the value for TAu_RoleInfo.RoleID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_RoleInfo.ID
     *
     * @return the value of TAu_RoleInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_RoleInfo.ID
     *
     * @param id the value for TAu_RoleInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_RoleInfo.RoleName
     *
     * @return the value of TAu_RoleInfo.RoleName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_RoleInfo.RoleName
     *
     * @param rolename the value for TAu_RoleInfo.RoleName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_RoleInfo.SortID
     *
     * @return the value of TAu_RoleInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Short getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_RoleInfo.SortID
     *
     * @param sortid the value for TAu_RoleInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSortid(Short sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAu_RoleInfo.State
     *
     * @return the value of TAu_RoleInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAu_RoleInfo.State
     *
     * @param state the value for TAu_RoleInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TauRoleinfo other = (TauRoleinfo) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRolename() == null ? other.getRolename() == null : this.getRolename().equals(other.getRolename()))
            && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRolename() == null) ? 0 : getRolename().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }
}