package com.shinowit.model;

import java.io.Serializable;
import java.util.Date;

public class TbaLoginfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.LogTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.IP
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_LogInfo.Content
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.ID
     *
     * @return the value of TBa_LogInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.ID
     *
     * @param id the value for TBa_LogInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.OperID
     *
     * @return the value of TBa_LogInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.OperID
     *
     * @param operid the value for TBa_LogInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.MenuID
     *
     * @return the value of TBa_LogInfo.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.MenuID
     *
     * @param menuid the value for TBa_LogInfo.MenuID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.LogTime
     *
     * @return the value of TBa_LogInfo.LogTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.LogTime
     *
     * @param logtime the value for TBa_LogInfo.LogTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.IP
     *
     * @return the value of TBa_LogInfo.IP
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.IP
     *
     * @param ip the value for TBa_LogInfo.IP
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_LogInfo.Content
     *
     * @return the value of TBa_LogInfo.Content
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_LogInfo.Content
     *
     * @param content the value for TBa_LogInfo.Content
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbaLoginfo other = (TbaLoginfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperid() == null ? other.getOperid() == null : this.getOperid().equals(other.getOperid()))
            && (this.getMenuid() == null ? other.getMenuid() == null : this.getMenuid().equals(other.getMenuid()))
            && (this.getLogtime() == null ? other.getLogtime() == null : this.getLogtime().equals(other.getLogtime()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperid() == null) ? 0 : getOperid().hashCode());
        result = prime * result + ((getMenuid() == null) ? 0 : getMenuid().hashCode());
        result = prime * result + ((getLogtime() == null) ? 0 : getLogtime().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}