package com.shinowit.model;

import java.io.Serializable;

public class TbaSupplierinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.SupplierName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String suppliername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.SupplierAB
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String supplierab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.LinkName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String linkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String linktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Integer sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplierInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBa_SupplierInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.SupplierID
     *
     * @return the value of TBa_SupplierInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.SupplierID
     *
     * @param supplierid the value for TBa_SupplierInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSupplierid(String supplierid) {
        this.supplierid = supplierid == null ? null : supplierid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.ID
     *
     * @return the value of TBa_SupplierInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.ID
     *
     * @param id the value for TBa_SupplierInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.SupplierName
     *
     * @return the value of TBa_SupplierInfo.SupplierName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.SupplierName
     *
     * @param suppliername the value for TBa_SupplierInfo.SupplierName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername == null ? null : suppliername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.SupplierAB
     *
     * @return the value of TBa_SupplierInfo.SupplierAB
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getSupplierab() {
        return supplierab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.SupplierAB
     *
     * @param supplierab the value for TBa_SupplierInfo.SupplierAB
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSupplierab(String supplierab) {
        this.supplierab = supplierab == null ? null : supplierab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.Address
     *
     * @return the value of TBa_SupplierInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.Address
     *
     * @param address the value for TBa_SupplierInfo.Address
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.LinkName
     *
     * @return the value of TBa_SupplierInfo.LinkName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.LinkName
     *
     * @param linkname the value for TBa_SupplierInfo.LinkName
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.LinkTel
     *
     * @return the value of TBa_SupplierInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.LinkTel
     *
     * @param linktel the value for TBa_SupplierInfo.LinkTel
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel == null ? null : linktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.QQ
     *
     * @return the value of TBa_SupplierInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.QQ
     *
     * @param qq the value for TBa_SupplierInfo.QQ
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.Email
     *
     * @return the value of TBa_SupplierInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.Email
     *
     * @param email the value for TBa_SupplierInfo.Email
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.SortID
     *
     * @return the value of TBa_SupplierInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.SortID
     *
     * @param sortid the value for TBa_SupplierInfo.SortID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplierInfo.State
     *
     * @return the value of TBa_SupplierInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplierInfo.State
     *
     * @param state the value for TBa_SupplierInfo.State
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplierInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbaSupplierinfo other = (TbaSupplierinfo) that;
        return (this.getSupplierid() == null ? other.getSupplierid() == null : this.getSupplierid().equals(other.getSupplierid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSuppliername() == null ? other.getSuppliername() == null : this.getSuppliername().equals(other.getSuppliername()))
            && (this.getSupplierab() == null ? other.getSupplierab() == null : this.getSupplierab().equals(other.getSupplierab()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLinkname() == null ? other.getLinkname() == null : this.getLinkname().equals(other.getLinkname()))
            && (this.getLinktel() == null ? other.getLinktel() == null : this.getLinktel().equals(other.getLinktel()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getSortid() == null ? other.getSortid() == null : this.getSortid().equals(other.getSortid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplierInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSupplierid() == null) ? 0 : getSupplierid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSuppliername() == null) ? 0 : getSuppliername().hashCode());
        result = prime * result + ((getSupplierab() == null) ? 0 : getSupplierab().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLinkname() == null) ? 0 : getLinkname().hashCode());
        result = prime * result + ((getLinktel() == null) ? 0 : getLinktel().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getSortid() == null) ? 0 : getSortid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }
}