package com.shinowit.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TmeInstockinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.BillCode
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.InType
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Byte intype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.InTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private Date intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.Handler
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.TotalMoney
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private BigDecimal totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMe_InStockInfo.Remark
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.BillCode
     *
     * @return the value of TMe_InStockInfo.BillCode
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.BillCode
     *
     * @param billcode the value for TMe_InStockInfo.BillCode
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode == null ? null : billcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.ID
     *
     * @return the value of TMe_InStockInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.ID
     *
     * @param id the value for TMe_InStockInfo.ID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.OperID
     *
     * @return the value of TMe_InStockInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.OperID
     *
     * @param operid the value for TMe_InStockInfo.OperID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.SupplierID
     *
     * @return the value of TMe_InStockInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.SupplierID
     *
     * @param supplierid the value for TMe_InStockInfo.SupplierID
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setSupplierid(String supplierid) {
        this.supplierid = supplierid == null ? null : supplierid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.InType
     *
     * @return the value of TMe_InStockInfo.InType
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Byte getIntype() {
        return intype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.InType
     *
     * @param intype the value for TMe_InStockInfo.InType
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setIntype(Byte intype) {
        this.intype = intype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.InTime
     *
     * @return the value of TMe_InStockInfo.InTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.InTime
     *
     * @param intime the value for TMe_InStockInfo.InTime
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.Handler
     *
     * @return the value of TMe_InStockInfo.Handler
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.Handler
     *
     * @param handler the value for TMe_InStockInfo.Handler
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.TotalMoney
     *
     * @return the value of TMe_InStockInfo.TotalMoney
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public BigDecimal getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.TotalMoney
     *
     * @param totalmoney the value for TMe_InStockInfo.TotalMoney
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setTotalmoney(BigDecimal totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMe_InStockInfo.Remark
     *
     * @return the value of TMe_InStockInfo.Remark
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMe_InStockInfo.Remark
     *
     * @param remark the value for TMe_InStockInfo.Remark
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TmeInstockinfo other = (TmeInstockinfo) that;
        return (this.getBillcode() == null ? other.getBillcode() == null : this.getBillcode().equals(other.getBillcode()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperid() == null ? other.getOperid() == null : this.getOperid().equals(other.getOperid()))
            && (this.getSupplierid() == null ? other.getSupplierid() == null : this.getSupplierid().equals(other.getSupplierid()))
            && (this.getIntype() == null ? other.getIntype() == null : this.getIntype().equals(other.getIntype()))
            && (this.getIntime() == null ? other.getIntime() == null : this.getIntime().equals(other.getIntime()))
            && (this.getHandler() == null ? other.getHandler() == null : this.getHandler().equals(other.getHandler()))
            && (this.getTotalmoney() == null ? other.getTotalmoney() == null : this.getTotalmoney().equals(other.getTotalmoney()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBillcode() == null) ? 0 : getBillcode().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperid() == null) ? 0 : getOperid().hashCode());
        result = prime * result + ((getSupplierid() == null) ? 0 : getSupplierid().hashCode());
        result = prime * result + ((getIntype() == null) ? 0 : getIntype().hashCode());
        result = prime * result + ((getIntime() == null) ? 0 : getIntime().hashCode());
        result = prime * result + ((getHandler() == null) ? 0 : getHandler().hashCode());
        result = prime * result + ((getTotalmoney() == null) ? 0 : getTotalmoney().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}