package com.shinowit.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TmeOrderinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    protected List<Criteria> oredCriteria;

    private int pageIndex;

    private int pageSize;

    private String customCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public TmeOrderinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPageIndex(int pageIndex) {
        this.pageIndex=pageIndex;
    }

    public int getPageIndex() {
        return this.pageIndex;
    }

    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    public int getPageSize() {
        return this.pageSize;
    }

    public void setCustomCriteria(String customCriteria) {
        this.customCriteria=customCriteria;
    }

    public String getCustomCriteria() {
        return this.customCriteria;
    }

    public int getSkipRecordCount() {
        int count=(this.pageIndex-1)*this.pageSize;
        if (count<0){
             count=0;
        }
        return count;
    }

    public int getEndRecordCount() {
        return this.pageIndex*this.pageSize;
    }

    public TmeOrderinfoExample(int pageSize, int pageIndex) {
        this();
        this.pageSize=pageSize;
        this.pageIndex=pageIndex;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBillcodeIsNull() {
            addCriterion("BillCode is null");
            return (Criteria) this;
        }

        public Criteria andBillcodeIsNotNull() {
            addCriterion("BillCode is not null");
            return (Criteria) this;
        }

        public Criteria andBillcodeEqualTo(String value) {
            addCriterion("BillCode =", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotEqualTo(String value) {
            addCriterion("BillCode <>", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeGreaterThan(String value) {
            addCriterion("BillCode >", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BillCode >=", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLessThan(String value) {
            addCriterion("BillCode <", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLessThanOrEqualTo(String value) {
            addCriterion("BillCode <=", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLike(String value) {
            addCriterion("BillCode like", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotLike(String value) {
            addCriterion("BillCode not like", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeIn(List<String> values) {
            addCriterion("BillCode in", values, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotIn(List<String> values) {
            addCriterion("BillCode not in", values, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeBetween(String value1, String value2) {
            addCriterion("BillCode between", value1, value2, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotBetween(String value1, String value2) {
            addCriterion("BillCode not between", value1, value2, "billcode");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("UserName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("UserName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("UserName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("UserName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("UserName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("UserName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("UserName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("UserName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("UserName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("UserName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("UserName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("UserName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("UserName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("UserName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andDeliveryidIsNull() {
            addCriterion("DeliveryID is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryidIsNotNull() {
            addCriterion("DeliveryID is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryidEqualTo(String value) {
            addCriterion("DeliveryID =", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidNotEqualTo(String value) {
            addCriterion("DeliveryID <>", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidGreaterThan(String value) {
            addCriterion("DeliveryID >", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidGreaterThanOrEqualTo(String value) {
            addCriterion("DeliveryID >=", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidLessThan(String value) {
            addCriterion("DeliveryID <", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidLessThanOrEqualTo(String value) {
            addCriterion("DeliveryID <=", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidLike(String value) {
            addCriterion("DeliveryID like", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidNotLike(String value) {
            addCriterion("DeliveryID not like", value, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidIn(List<String> values) {
            addCriterion("DeliveryID in", values, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidNotIn(List<String> values) {
            addCriterion("DeliveryID not in", values, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidBetween(String value1, String value2) {
            addCriterion("DeliveryID between", value1, value2, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andDeliveryidNotBetween(String value1, String value2) {
            addCriterion("DeliveryID not between", value1, value2, "deliveryid");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OperID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OperID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OperID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OperID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OperID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OperID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OperID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OperID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OperID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OperID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OperID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OperID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OperID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OperID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeIsNull() {
            addCriterion("OutBillCode is null");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeIsNotNull() {
            addCriterion("OutBillCode is not null");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeEqualTo(String value) {
            addCriterion("OutBillCode =", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeNotEqualTo(String value) {
            addCriterion("OutBillCode <>", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeGreaterThan(String value) {
            addCriterion("OutBillCode >", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeGreaterThanOrEqualTo(String value) {
            addCriterion("OutBillCode >=", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeLessThan(String value) {
            addCriterion("OutBillCode <", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeLessThanOrEqualTo(String value) {
            addCriterion("OutBillCode <=", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeLike(String value) {
            addCriterion("OutBillCode like", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeNotLike(String value) {
            addCriterion("OutBillCode not like", value, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeIn(List<String> values) {
            addCriterion("OutBillCode in", values, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeNotIn(List<String> values) {
            addCriterion("OutBillCode not in", values, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeBetween(String value1, String value2) {
            addCriterion("OutBillCode between", value1, value2, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeNotBetween(String value1, String value2) {
            addCriterion("OutBillCode not between", value1, value2, "outbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeIsNull() {
            addCriterion("PostBillCode is null");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeIsNotNull() {
            addCriterion("PostBillCode is not null");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeEqualTo(String value) {
            addCriterion("PostBillCode =", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeNotEqualTo(String value) {
            addCriterion("PostBillCode <>", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeGreaterThan(String value) {
            addCriterion("PostBillCode >", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PostBillCode >=", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeLessThan(String value) {
            addCriterion("PostBillCode <", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeLessThanOrEqualTo(String value) {
            addCriterion("PostBillCode <=", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeLike(String value) {
            addCriterion("PostBillCode like", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeNotLike(String value) {
            addCriterion("PostBillCode not like", value, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeIn(List<String> values) {
            addCriterion("PostBillCode in", values, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeNotIn(List<String> values) {
            addCriterion("PostBillCode not in", values, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeBetween(String value1, String value2) {
            addCriterion("PostBillCode between", value1, value2, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeNotBetween(String value1, String value2) {
            addCriterion("PostBillCode not between", value1, value2, "postbillcode");
            return (Criteria) this;
        }

        public Criteria andBillstatusIsNull() {
            addCriterion("BillStatus is null");
            return (Criteria) this;
        }

        public Criteria andBillstatusIsNotNull() {
            addCriterion("BillStatus is not null");
            return (Criteria) this;
        }

        public Criteria andBillstatusEqualTo(Byte value) {
            addCriterion("BillStatus =", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusNotEqualTo(Byte value) {
            addCriterion("BillStatus <>", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusGreaterThan(Byte value) {
            addCriterion("BillStatus >", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("BillStatus >=", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusLessThan(Byte value) {
            addCriterion("BillStatus <", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusLessThanOrEqualTo(Byte value) {
            addCriterion("BillStatus <=", value, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusIn(List<Byte> values) {
            addCriterion("BillStatus in", values, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusNotIn(List<Byte> values) {
            addCriterion("BillStatus not in", values, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusBetween(Byte value1, Byte value2) {
            addCriterion("BillStatus between", value1, value2, "billstatus");
            return (Criteria) this;
        }

        public Criteria andBillstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("BillStatus not between", value1, value2, "billstatus");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("OrderTime is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("OrderTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(Date value) {
            addCriterion("OrderTime =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(Date value) {
            addCriterion("OrderTime <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(Date value) {
            addCriterion("OrderTime >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OrderTime >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(Date value) {
            addCriterion("OrderTime <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(Date value) {
            addCriterion("OrderTime <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<Date> values) {
            addCriterion("OrderTime in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<Date> values) {
            addCriterion("OrderTime not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(Date value1, Date value2) {
            addCriterion("OrderTime between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(Date value1, Date value2) {
            addCriterion("OrderTime not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andRecmanIsNull() {
            addCriterion("RecMan is null");
            return (Criteria) this;
        }

        public Criteria andRecmanIsNotNull() {
            addCriterion("RecMan is not null");
            return (Criteria) this;
        }

        public Criteria andRecmanEqualTo(String value) {
            addCriterion("RecMan =", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanNotEqualTo(String value) {
            addCriterion("RecMan <>", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanGreaterThan(String value) {
            addCriterion("RecMan >", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanGreaterThanOrEqualTo(String value) {
            addCriterion("RecMan >=", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanLessThan(String value) {
            addCriterion("RecMan <", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanLessThanOrEqualTo(String value) {
            addCriterion("RecMan <=", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanLike(String value) {
            addCriterion("RecMan like", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanNotLike(String value) {
            addCriterion("RecMan not like", value, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanIn(List<String> values) {
            addCriterion("RecMan in", values, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanNotIn(List<String> values) {
            addCriterion("RecMan not in", values, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanBetween(String value1, String value2) {
            addCriterion("RecMan between", value1, value2, "recman");
            return (Criteria) this;
        }

        public Criteria andRecmanNotBetween(String value1, String value2) {
            addCriterion("RecMan not between", value1, value2, "recman");
            return (Criteria) this;
        }

        public Criteria andLinktelIsNull() {
            addCriterion("LinkTel is null");
            return (Criteria) this;
        }

        public Criteria andLinktelIsNotNull() {
            addCriterion("LinkTel is not null");
            return (Criteria) this;
        }

        public Criteria andLinktelEqualTo(String value) {
            addCriterion("LinkTel =", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotEqualTo(String value) {
            addCriterion("LinkTel <>", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelGreaterThan(String value) {
            addCriterion("LinkTel >", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelGreaterThanOrEqualTo(String value) {
            addCriterion("LinkTel >=", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelLessThan(String value) {
            addCriterion("LinkTel <", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelLessThanOrEqualTo(String value) {
            addCriterion("LinkTel <=", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelLike(String value) {
            addCriterion("LinkTel like", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotLike(String value) {
            addCriterion("LinkTel not like", value, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelIn(List<String> values) {
            addCriterion("LinkTel in", values, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotIn(List<String> values) {
            addCriterion("LinkTel not in", values, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelBetween(String value1, String value2) {
            addCriterion("LinkTel between", value1, value2, "linktel");
            return (Criteria) this;
        }

        public Criteria andLinktelNotBetween(String value1, String value2) {
            addCriterion("LinkTel not between", value1, value2, "linktel");
            return (Criteria) this;
        }

        public Criteria andRecaddressIsNull() {
            addCriterion("RecAddress is null");
            return (Criteria) this;
        }

        public Criteria andRecaddressIsNotNull() {
            addCriterion("RecAddress is not null");
            return (Criteria) this;
        }

        public Criteria andRecaddressEqualTo(String value) {
            addCriterion("RecAddress =", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressNotEqualTo(String value) {
            addCriterion("RecAddress <>", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressGreaterThan(String value) {
            addCriterion("RecAddress >", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressGreaterThanOrEqualTo(String value) {
            addCriterion("RecAddress >=", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressLessThan(String value) {
            addCriterion("RecAddress <", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressLessThanOrEqualTo(String value) {
            addCriterion("RecAddress <=", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressLike(String value) {
            addCriterion("RecAddress like", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressNotLike(String value) {
            addCriterion("RecAddress not like", value, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressIn(List<String> values) {
            addCriterion("RecAddress in", values, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressNotIn(List<String> values) {
            addCriterion("RecAddress not in", values, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressBetween(String value1, String value2) {
            addCriterion("RecAddress between", value1, value2, "recaddress");
            return (Criteria) this;
        }

        public Criteria andRecaddressNotBetween(String value1, String value2) {
            addCriterion("RecAddress not between", value1, value2, "recaddress");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("PostCode is null");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("PostCode is not null");
            return (Criteria) this;
        }

        public Criteria andPostcodeEqualTo(String value) {
            addCriterion("PostCode =", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotEqualTo(String value) {
            addCriterion("PostCode <>", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThan(String value) {
            addCriterion("PostCode >", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PostCode >=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThan(String value) {
            addCriterion("PostCode <", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(String value) {
            addCriterion("PostCode <=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLike(String value) {
            addCriterion("PostCode like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotLike(String value) {
            addCriterion("PostCode not like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeIn(List<String> values) {
            addCriterion("PostCode in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotIn(List<String> values) {
            addCriterion("PostCode not in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeBetween(String value1, String value2) {
            addCriterion("PostCode between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotBetween(String value1, String value2) {
            addCriterion("PostCode not between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyIsNull() {
            addCriterion("TotalMoney is null");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyIsNotNull() {
            addCriterion("TotalMoney is not null");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyEqualTo(BigDecimal value) {
            addCriterion("TotalMoney =", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyNotEqualTo(BigDecimal value) {
            addCriterion("TotalMoney <>", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyGreaterThan(BigDecimal value) {
            addCriterion("TotalMoney >", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalMoney >=", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyLessThan(BigDecimal value) {
            addCriterion("TotalMoney <", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalMoney <=", value, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyIn(List<BigDecimal> values) {
            addCriterion("TotalMoney in", values, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyNotIn(List<BigDecimal> values) {
            addCriterion("TotalMoney not in", values, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalMoney between", value1, value2, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andTotalmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalMoney not between", value1, value2, "totalmoney");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBillcodeLikeInsensitive(String value) {
            addCriterion("upper(BillCode) like", value.toUpperCase(), "billcode");
            return (Criteria) this;
        }

        public Criteria andUsernameLikeInsensitive(String value) {
            addCriterion("upper(UserName) like", value.toUpperCase(), "username");
            return (Criteria) this;
        }

        public Criteria andDeliveryidLikeInsensitive(String value) {
            addCriterion("upper(DeliveryID) like", value.toUpperCase(), "deliveryid");
            return (Criteria) this;
        }

        public Criteria andOperidLikeInsensitive(String value) {
            addCriterion("upper(OperID) like", value.toUpperCase(), "operid");
            return (Criteria) this;
        }

        public Criteria andOutbillcodeLikeInsensitive(String value) {
            addCriterion("upper(OutBillCode) like", value.toUpperCase(), "outbillcode");
            return (Criteria) this;
        }

        public Criteria andPostbillcodeLikeInsensitive(String value) {
            addCriterion("upper(PostBillCode) like", value.toUpperCase(), "postbillcode");
            return (Criteria) this;
        }

        public Criteria andRecmanLikeInsensitive(String value) {
            addCriterion("upper(RecMan) like", value.toUpperCase(), "recman");
            return (Criteria) this;
        }

        public Criteria andLinktelLikeInsensitive(String value) {
            addCriterion("upper(LinkTel) like", value.toUpperCase(), "linktel");
            return (Criteria) this;
        }

        public Criteria andRecaddressLikeInsensitive(String value) {
            addCriterion("upper(RecAddress) like", value.toUpperCase(), "recaddress");
            return (Criteria) this;
        }

        public Criteria andPostcodeLikeInsensitive(String value) {
            addCriterion("upper(PostCode) like", value.toUpperCase(), "postcode");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(Remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 29 09:56:18 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMe_OrderInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}