package com.shinowit.dao.mapper;

import com.shinowit.model.TbaMemberinfo;
import com.shinowit.model.TbaMemberinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaMemberinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int countByExample(TbaMemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int deleteByExample(TbaMemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int insert(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int insertSelective(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    List<TbaMemberinfo> selectByExample(TbaMemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    TbaMemberinfo selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbaMemberinfo record, @Param("example") TbaMemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int updateByExample(@Param("record") TbaMemberinfo record, @Param("example") TbaMemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int updateByPrimaryKeySelective(TbaMemberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MemberInfo
     *
     * @mbggenerated Mon Dec 29 09:56:18 CST 2014
     */
    int updateByPrimaryKey(TbaMemberinfo record);

    List<TbaMemberinfo> selectPage(TbaMemberinfoExample example);

    String selectMaxPrimaryKeyValue();
}